### ISSUE TITLE
[suggestion] export addressSchema

### ISSUE THREAD

**Issue by sakulstra** [lukemadera/meteor-autoform-googleplace#12]
Hay,
why don't you simply add the AddressSchema to this package and export it? So we wouldn't need to copy paste it if we want to use this plugin ;)

Regards,
Lukas

edit: okay perhaps it isn't that easy because your state regex, only allows some specific states, but would always fail in European country

**Comment by lukemadera** [comment]
Yeah, I want to keep flexibility. Copy and paste isn't too hard ;)
