### ISSUE TITLE
Support GeoJSON For coordinates

### ISSUE THREAD

**Issue by praveenkoka** [lukemadera/meteor-autoform-googleplace#2]
@lukemadera It would be great if the location could be saved in a GeoJSON format, as against the current lat and lng. Example is below. Reference( http://geojson.org/ , http://docs.mongodb.org/v2.6/reference/operator/query/near/#query-on-geojson-data)

```
{
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1] // [ lng, lat ]
  },
}
```

That would enable geospatial queries on mongo.

**Comment by lukemadera** [comment]
Sounds good @praveenkoka - I'll be fairly busy the next day or so but I'll look into it when I can!

**Comment by praveenkoka** [comment]
@lukemadera awesome! I forked your repo and wrote some code to test locally - https://github.com/praveenkoka/meteor-autoform-googleplace

**Comment by lukemadera** [comment]
sorry @praveenkoka - been a hectic week and I'm off to Thailand for 2 weeks early tomorrow morning so I won't get to this until I get back!

**Comment by zeroasterisk** [comment]
:+1:

**Comment by lukemadera** [comment]
@praveenkoka been swamped but finally catching up and should be much more responsive now! Let me know if you have any further issues with this!

**Comment by praveenkoka** [comment]
@lukemadera Awesome thanks!
