### ISSUE TITLE
Array of addresses

### ISSUE THREAD

**Issue by kizim** [lukemadera/meteor-autoform-googleplace#24]
I have the schema for my addresses field:

```
citiesToWork: {
  type: [Object],
  label: 'Cities',
  blackbox: true,
  optional: true
},
```

And in template:
`{{> afQuickField name='citiesToWork' type='googleplace' opts=optsGoogleplaceCity}}`

But it only show 1 field to type address, not autoform block for adding values to array. 
Is there any way to create an element for adding several addresses?

**Comment by acomito** [comment]
I would do something like this:

```
Schemas = {};

Schemas.Address = new SimpleSchema({
    fullAddress: {
        type: String
    },
    lat: {
        type: Number,
        decimal: true
    },
    lng: {
        type: Number,
        decimal: true
    },
    geometry: {
        type: Object,
        blackbox: true
    },
    placeId: {
        type: String
    },
    street: {
        type: String,
        max: 100
    },
    city: {
        type: String,
        max: 50
    },
    state: {
        type: String,
    },
    zip: {
        type: String,
    },
    country: {
        type: String
    },
});



Schemas.MainSchema = new SimpleSchema({
    cities: {
        type: [Schemas.Address],
        optional: true
    }
});


MainSchema = new Mongo.Collection("MainSchema");

MainSchema.attachSchema(Schemas.MainSchema);


MainSchema.allow({
    insert: function () { return true; },
    update: function () { return true; },
    remove: function () { return true; }
});


```

**Comment by leizard** [comment]
Hi @acomito, I did the same code as your recommendation but it doesn't work. Still show only 1 field of address.

**Comment by acomito** [comment]
maybe this inside a custom template?

{{> afFormGroup name=this.current.location class='lm-autoform-google-place-input' template='plain' label="Other Location" placeholder="full street address please..."}}

which is pointed to by this:

{{> afQuickField name="otherLocations" class="form-control" autocomplete="off" template="otherLocations" label=false}}

in this example, my array is schema field "otherLocations" and the template name is otherLocations

**Comment by leizard** [comment]
Hi @acomito, how is template `otherLocations` defined ?
Sorry I'm new to autoform.
