### ISSUE TITLE
Return Place Name in Object also

### ISSUE THREAD

**Issue by xpluscal** [lukemadera/meteor-autoform-googleplace#5]
Is it possible to retrieve the name of the selected place as well, if available?

**Comment by lukemadera** [comment]
What do you mean `name`? Could you give me an example of what you're looking for?

**Comment by znat** [comment]
I think he meant it would be useful to have the whole Place object returned: id, name, opening hours, etc.
I second that.

**Comment by xpluscal** [comment]
Yes, exactly.
I think the Place-ID would be sufficient to be stored in the database to retrieve all the other information later, when needed.
