### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by mats68** [lukemadera/meteor-autoform-googleplace#7]
Can I just filter the dropdown so that it just displays cities ?

**Comment by lukemadera** [comment]
So rather than displaying addresses you just want cities? I would think so yes.

**Comment by mats68** [comment]
Hello I tried this, but it still displays countries and other stuff:

`
    optsGoogleplace: function () {
        return {
          googleOptions: {
            types: ['(cities)'],
            componentRestrictions: { country: "ch" }
          }
        }
      }
`

**Comment by lukemadera** [comment]
Working fine for me, demo updated below - the 2nd input only returns cities:
http://lukemadera-packages.meteor.com/af-googleplace-basic

``` js
googleOptions: {
          types: ['(cities)'],
          componentRestrictions: { country:'us' }
        }
```
